schemaVersion: "2.0.0"

commandTests:
  - name: "PHP Version Check"
    command: "php"
    args: ["--version"]
    expectedOutput:
      # (?m) will allow ^ and $ to match individual lines not start and end of entire string
      - "(?m)^PHP 8\\.5\\.[0-9]+ \\(cli\\)"

  - name: "Sodium Module Loaded"
    command: "php"
    args: ["-m"]
    expectedOutput:
      - "(?m)^sodium"
    excludedOutput:
      - "(?m)^xmlrpc"

  - name: "Sodium XMLRPC Configuration Check"
    command: "php"
    args: ["-i"]
    expectedOutput:
      # Sodium
      - "(?m)^/etc/php.d/20-sodium.ini"
      - "(?m)^sodium support => enabled$"
      - "(?m)^libsodium headers version => [0-9]+(\\.[0-9]+){2,}$"
    excludedOutput:
      # XMLRPC
      - "(?m)^/etc/php.d/30-xmlrpc.ini"
      - "(?m)^core library version => xmlrpc-epi v."

  # Swoole is not currently supported on PHP 8.5
  - name: "No Swoole Module Check"
    command: "php"
    args: ["-m"]
    excludedOutput:
      - "(?m)^swoole"
