name: Docker Image MailHog
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *" # 6 AM Daily
  push:
    paths:
      - mailhog/**
      - .github/workflows/mailhog.yml

jobs:
  mailhog:
    name: MailHog
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.0"

    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v6
        with:
          context: mailhog
          platforms: linux/amd64,linux/arm64
          build-args: MAILHOG_VERSION=${{ matrix.version }}
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/mailhog:${{ matrix.version }},wardenenv/mailhog:${{ matrix.version }}
